<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        // [iso2, name, iso3, phone_code, capital, currency_code, currency_name, currency_symbol, region, subregion]
        $countries = [
            // ── Africa ────────────────────────────────────────────────────────────
            ['DZ','Algeria','DZA','213','Algiers','DZD','Algerian Dinar','دج','Africa','Northern Africa'],
            ['AO','Angola','AGO','244','Luanda','AOA','Angolan Kwanza','Kz','Africa','Middle Africa'],
            ['BJ','Benin','BEN','229','Porto-Novo','XOF','West African CFA Franc','Fr','Africa','Western Africa'],
            ['BW','Botswana','BWA','267','Gaborone','BWP','Botswana Pula','P','Africa','Southern Africa'],
            ['BF','Burkina Faso','BFA','226','Ouagadougou','XOF','West African CFA Franc','Fr','Africa','Western Africa'],
            ['BI','Burundi','BDI','257','Gitega','BIF','Burundian Franc','Fr','Africa','Eastern Africa'],
            ['CV','Cabo Verde','CPV','238','Praia','CVE','Cape Verdean Escudo','$','Africa','Western Africa'],
            ['CM','Cameroon','CMR','237','Yaoundé','XAF','Central African CFA Franc','Fr','Africa','Middle Africa'],
            ['CF','Central African Republic','CAF','236','Bangui','XAF','Central African CFA Franc','Fr','Africa','Middle Africa'],
            ['TD','Chad','TCD','235',"N'Djamena",'XAF','Central African CFA Franc','Fr','Africa','Middle Africa'],
            ['KM','Comoros','COM','269','Moroni','KMF','Comorian Franc','Fr','Africa','Eastern Africa'],
            ['CG','Congo (Brazzaville)','COG','242','Brazzaville','XAF','Central African CFA Franc','Fr','Africa','Middle Africa'],
            ['CD','Congo (DRC)','COD','243','Kinshasa','CDF','Congolese Franc','Fr','Africa','Middle Africa'],
            ['DJ','Djibouti','DJI','253','Djibouti City','DJF','Djiboutian Franc','Fr','Africa','Eastern Africa'],
            ['EG','Egypt','EGY','20','Cairo','EGP','Egyptian Pound','£','Africa','Northern Africa'],
            ['GQ','Equatorial Guinea','GNQ','240','Malabo','XAF','Central African CFA Franc','Fr','Africa','Middle Africa'],
            ['ER','Eritrea','ERI','291','Asmara','ERN','Eritrean Nakfa','Nfk','Africa','Eastern Africa'],
            ['SZ','Eswatini','SWZ','268','Mbabane','SZL','Swazi Lilangeni','L','Africa','Southern Africa'],
            ['ET','Ethiopia','ETH','251','Addis Ababa','ETB','Ethiopian Birr','Br','Africa','Eastern Africa'],
            ['GA','Gabon','GAB','241','Libreville','XAF','Central African CFA Franc','Fr','Africa','Middle Africa'],
            ['GM','Gambia','GMB','220','Banjul','GMD','Gambian Dalasi','D','Africa','Western Africa'],
            ['GH','Ghana','GHA','233','Accra','GHS','Ghanaian Cedi','₵','Africa','Western Africa'],
            ['GN','Guinea','GIN','224','Conakry','GNF','Guinean Franc','Fr','Africa','Western Africa'],
            ['GW','Guinea-Bissau','GNB','245','Bissau','XOF','West African CFA Franc','Fr','Africa','Western Africa'],
            ['CI','Ivory Coast','CIV','225','Yamoussoukro','XOF','West African CFA Franc','Fr','Africa','Western Africa'],
            ['KE','Kenya','KEN','254','Nairobi','KES','Kenyan Shilling','KSh','Africa','Eastern Africa'],
            ['LS','Lesotho','LSO','266','Maseru','LSL','Lesotho Loti','L','Africa','Southern Africa'],
            ['LR','Liberia','LBR','231','Monrovia','LRD','Liberian Dollar','$','Africa','Western Africa'],
            ['LY','Libya','LBY','218','Tripoli','LYD','Libyan Dinar','LD','Africa','Northern Africa'],
            ['MG','Madagascar','MDG','261','Antananarivo','MGA','Malagasy Ariary','Ar','Africa','Eastern Africa'],
            ['MW','Malawi','MWI','265','Lilongwe','MWK','Malawian Kwacha','MK','Africa','Eastern Africa'],
            ['ML','Mali','MLI','223','Bamako','XOF','West African CFA Franc','Fr','Africa','Western Africa'],
            ['MR','Mauritania','MRT','222','Nouakchott','MRU','Mauritanian Ouguiya','UM','Africa','Western Africa'],
            ['MU','Mauritius','MUS','230','Port Louis','MUR','Mauritian Rupee','₨','Africa','Eastern Africa'],
            ['MA','Morocco','MAR','212','Rabat','MAD','Moroccan Dirham','MAD','Africa','Northern Africa'],
            ['MZ','Mozambique','MOZ','258','Maputo','MZN','Mozambican Metical','MT','Africa','Eastern Africa'],
            ['NA','Namibia','NAM','264','Windhoek','NAD','Namibian Dollar','$','Africa','Southern Africa'],
            ['NE','Niger','NER','227','Niamey','XOF','West African CFA Franc','Fr','Africa','Western Africa'],
            ['NG','Nigeria','NGA','234','Abuja','NGN','Nigerian Naira','₦','Africa','Western Africa'],
            ['RW','Rwanda','RWA','250','Kigali','RWF','Rwandan Franc','Fr','Africa','Eastern Africa'],
            ['ST','São Tomé and Príncipe','STP','239','São Tomé','STN','Dobra','Db','Africa','Middle Africa'],
            ['SN','Senegal','SEN','221','Dakar','XOF','West African CFA Franc','Fr','Africa','Western Africa'],
            ['SC','Seychelles','SYC','248','Victoria','SCR','Seychellois Rupee','₨','Africa','Eastern Africa'],
            ['SL','Sierra Leone','SLE','232','Freetown','SLL','Sierra Leonean Leone','Le','Africa','Western Africa'],
            ['SO','Somalia','SOM','252','Mogadishu','SOS','Somali Shilling','Sh','Africa','Eastern Africa'],
            ['ZA','South Africa','ZAF','27','Pretoria','ZAR','South African Rand','R','Africa','Southern Africa'],
            ['SS','South Sudan','SSD','211','Juba','SSP','South Sudanese Pound','£','Africa','Eastern Africa'],
            ['SD','Sudan','SDN','249','Khartoum','SDG','Sudanese Pound','£','Africa','Northern Africa'],
            ['TZ','Tanzania','TZA','255','Dodoma','TZS','Tanzanian Shilling','Sh','Africa','Eastern Africa'],
            ['TG','Togo','TGO','228','Lomé','XOF','West African CFA Franc','Fr','Africa','Western Africa'],
            ['TN','Tunisia','TUN','216','Tunis','TND','Tunisian Dinar','د.ت','Africa','Northern Africa'],
            ['UG','Uganda','UGA','256','Kampala','UGX','Ugandan Shilling','Sh','Africa','Eastern Africa'],
            ['ZM','Zambia','ZMB','260','Lusaka','ZMW','Zambian Kwacha','ZK','Africa','Eastern Africa'],
            ['ZW','Zimbabwe','ZWE','263','Harare','ZWL','Zimbabwean Dollar','$','Africa','Eastern Africa'],

            // ── Asia ──────────────────────────────────────────────────────────────
            ['AF','Afghanistan','AFG','93','Kabul','AFN','Afghan Afghani','؋','Asia','Southern Asia'],
            ['AM','Armenia','ARM','374','Yerevan','AMD','Armenian Dram','֏','Asia','Western Asia'],
            ['AZ','Azerbaijan','AZE','994','Baku','AZN','Azerbaijani Manat','₼','Asia','Western Asia'],
            ['BH','Bahrain','BHR','973','Manama','BHD','Bahraini Dinar','.د.ب','Asia','Western Asia'],
            ['BD','Bangladesh','BGD','880','Dhaka','BDT','Bangladeshi Taka','৳','Asia','Southern Asia'],
            ['BT','Bhutan','BTN','975','Thimphu','BTN','Bhutanese Ngultrum','Nu','Asia','Southern Asia'],
            ['BN','Brunei','BRN','673','Bandar Seri Begawan','BND','Brunei Dollar','$','Asia','South-Eastern Asia'],
            ['KH','Cambodia','KHM','855','Phnom Penh','KHR','Cambodian Riel','៛','Asia','South-Eastern Asia'],
            ['CN','China','CHN','86','Beijing','CNY','Chinese Yuan','¥','Asia','Eastern Asia'],
            ['CY','Cyprus','CYP','357','Nicosia','EUR','Euro','€','Asia','Western Asia'],
            ['GE','Georgia','GEO','995','Tbilisi','GEL','Georgian Lari','₾','Asia','Western Asia'],
            ['IN','India','IND','91','New Delhi','INR','Indian Rupee','₹','Asia','Southern Asia'],
            ['ID','Indonesia','IDN','62','Jakarta','IDR','Indonesian Rupiah','Rp','Asia','South-Eastern Asia'],
            ['IR','Iran','IRN','98','Tehran','IRR','Iranian Rial','﷼','Asia','Southern Asia'],
            ['IQ','Iraq','IRQ','964','Baghdad','IQD','Iraqi Dinar','ع.د','Asia','Western Asia'],
            ['IL','Israel','ISR','972','Jerusalem','ILS','Israeli New Shekel','₪','Asia','Western Asia'],
            ['JP','Japan','JPN','81','Tokyo','JPY','Japanese Yen','¥','Asia','Eastern Asia'],
            ['JO','Jordan','JOR','962','Amman','JOD','Jordanian Dinar','د.ا','Asia','Western Asia'],
            ['KZ','Kazakhstan','KAZ','7','Astana','KZT','Kazakhstani Tenge','₸','Asia','Central Asia'],
            ['KW','Kuwait','KWT','965','Kuwait City','KWD','Kuwaiti Dinar','د.ك','Asia','Western Asia'],
            ['KG','Kyrgyzstan','KGZ','996','Bishkek','KGS','Kyrgystani Som','с','Asia','Central Asia'],
            ['LA','Laos','LAO','856','Vientiane','LAK','Lao Kip','₭','Asia','South-Eastern Asia'],
            ['LB','Lebanon','LBN','961','Beirut','LBP','Lebanese Pound','ل.ل','Asia','Western Asia'],
            ['MY','Malaysia','MYS','60','Kuala Lumpur','MYR','Malaysian Ringgit','RM','Asia','South-Eastern Asia'],
            ['MV','Maldives','MDV','960','Malé','MVR','Maldivian Rufiyaa','Rf','Asia','Southern Asia'],
            ['MN','Mongolia','MNG','976','Ulaanbaatar','MNT','Mongolian Tögrög','₮','Asia','Eastern Asia'],
            ['MM','Myanmar','MMR','95','Naypyidaw','MMK','Myanmar Kyat','K','Asia','South-Eastern Asia'],
            ['NP','Nepal','NPL','977','Kathmandu','NPR','Nepalese Rupee','₨','Asia','Southern Asia'],
            ['KP','North Korea','PRK','850','Pyongyang','KPW','North Korean Won','₩','Asia','Eastern Asia'],
            ['OM','Oman','OMN','968','Muscat','OMR','Omani Rial','ر.ع.','Asia','Western Asia'],
            ['PK','Pakistan','PAK','92','Islamabad','PKR','Pakistani Rupee','₨','Asia','Southern Asia'],
            ['PS','Palestine','PSE','970','Ramallah','ILS','Israeli New Shekel','₪','Asia','Western Asia'],
            ['PH','Philippines','PHL','63','Manila','PHP','Philippine Peso','₱','Asia','South-Eastern Asia'],
            ['QA','Qatar','QAT','974','Doha','QAR','Qatari Riyal','ر.ق','Asia','Western Asia'],
            ['SA','Saudi Arabia','SAU','966','Riyadh','SAR','Saudi Riyal','ر.س','Asia','Western Asia'],
            ['SG','Singapore','SGP','65','Singapore','SGD','Singapore Dollar','$','Asia','South-Eastern Asia'],
            ['KR','South Korea','KOR','82','Seoul','KRW','South Korean Won','₩','Asia','Eastern Asia'],
            ['LK','Sri Lanka','LKA','94','Sri Jayawardenepura Kotte','LKR','Sri Lankan Rupee','₨','Asia','Southern Asia'],
            ['SY','Syria','SYR','963','Damascus','SYP','Syrian Pound','£','Asia','Western Asia'],
            ['TW','Taiwan','TWN','886','Taipei','TWD','New Taiwan Dollar','$','Asia','Eastern Asia'],
            ['TJ','Tajikistan','TJK','992','Dushanbe','TJS','Tajikistani Somoni','SM','Asia','Central Asia'],
            ['TH','Thailand','THA','66','Bangkok','THB','Thai Baht','฿','Asia','South-Eastern Asia'],
            ['TL','Timor-Leste','TLS','670','Dili','USD','US Dollar','$','Asia','South-Eastern Asia'],
            ['TR','Türkiye','TUR','90','Ankara','TRY','Turkish Lira','₺','Asia','Western Asia'],
            ['TM','Turkmenistan','TKM','993','Ashgabat','TMT','Turkmenistani Manat','T','Asia','Central Asia'],
            ['AE','United Arab Emirates','ARE','971','Abu Dhabi','AED','UAE Dirham','د.إ','Asia','Western Asia'],
            ['UZ','Uzbekistan','UZB','998','Tashkent','UZS','Uzbekistani Som',"So'm",'Asia','Central Asia'],
            ['VN','Vietnam','VNM','84','Hanoi','VND','Vietnamese Đồng','₫','Asia','South-Eastern Asia'],
            ['YE','Yemen','YEM','967','Sanaa','YER','Yemeni Rial','﷼','Asia','Western Asia'],

            // ── Europe ────────────────────────────────────────────────────────────
            ['AL','Albania','ALB','355','Tirana','ALL','Albanian Lek','L','Europe','Southern Europe'],
            ['AD','Andorra','AND','376','Andorra la Vella','EUR','Euro','€','Europe','Southern Europe'],
            ['AT','Austria','AUT','43','Vienna','EUR','Euro','€','Europe','Western Europe'],
            ['BY','Belarus','BLR','375','Minsk','BYR','Belarusian Ruble','Br','Europe','Eastern Europe'],
            ['BE','Belgium','BEL','32','Brussels','EUR','Euro','€','Europe','Western Europe'],
            ['BA','Bosnia and Herzegovina','BIH','387','Sarajevo','BAM','Convertible Mark','KM','Europe','Southern Europe'],
            ['BG','Bulgaria','BGR','359','Sofia','BGN','Bulgarian Lev','лв','Europe','Eastern Europe'],
            ['HR','Croatia','HRV','385','Zagreb','EUR','Euro','€','Europe','Southern Europe'],
            ['CZ','Czech Republic','CZE','420','Prague','CZK','Czech Koruna','Kč','Europe','Eastern Europe'],
            ['DK','Denmark','DNK','45','Copenhagen','DKK','Danish Krone','kr','Europe','Northern Europe'],
            ['EE','Estonia','EST','372','Tallinn','EUR','Euro','€','Europe','Northern Europe'],
            ['FI','Finland','FIN','358','Helsinki','EUR','Euro','€','Europe','Northern Europe'],
            ['FR','France','FRA','33','Paris','EUR','Euro','€','Europe','Western Europe'],
            ['DE','Germany','DEU','49','Berlin','EUR','Euro','€','Europe','Western Europe'],
            ['GR','Greece','GRC','30','Athens','EUR','Euro','€','Europe','Southern Europe'],
            ['HU','Hungary','HUN','36','Budapest','HUF','Hungarian Forint','Ft','Europe','Eastern Europe'],
            ['IS','Iceland','ISL','354','Reykjavik','ISK','Icelandic Króna','kr','Europe','Northern Europe'],
            ['IE','Ireland','IRL','353','Dublin','EUR','Euro','€','Europe','Northern Europe'],
            ['IT','Italy','ITA','39','Rome','EUR','Euro','€','Europe','Southern Europe'],
            ['XK','Kosovo','XKX','383','Pristina','EUR','Euro','€','Europe','Southern Europe'],
            ['LV','Latvia','LVA','371','Riga','EUR','Euro','€','Europe','Northern Europe'],
            ['LI','Liechtenstein','LIE','423','Vaduz','CHF','Swiss Franc','Fr','Europe','Western Europe'],
            ['LT','Lithuania','LTU','370','Vilnius','EUR','Euro','€','Europe','Northern Europe'],
            ['LU','Luxembourg','LUX','352','Luxembourg City','EUR','Euro','€','Europe','Western Europe'],
            ['MT','Malta','MLT','356','Valletta','EUR','Euro','€','Europe','Southern Europe'],
            ['MD','Moldova','MDA','373','Chișinău','MDL','Moldovan Leu','L','Europe','Eastern Europe'],
            ['MC','Monaco','MCO','377','Monaco','EUR','Euro','€','Europe','Western Europe'],
            ['ME','Montenegro','MNE','382','Podgorica','EUR','Euro','€','Europe','Southern Europe'],
            ['NL','Netherlands','NLD','31','Amsterdam','EUR','Euro','€','Europe','Western Europe'],
            ['MK','North Macedonia','MKD','389','Skopje','MKD','Macedonian Denar','ден','Europe','Southern Europe'],
            ['NO','Norway','NOR','47','Oslo','NOK','Norwegian Krone','kr','Europe','Northern Europe'],
            ['PL','Poland','POL','48','Warsaw','PLN','Polish Złoty','zł','Europe','Eastern Europe'],
            ['PT','Portugal','PRT','351','Lisbon','EUR','Euro','€','Europe','Southern Europe'],
            ['RO','Romania','ROU','40','Bucharest','RON','Romanian Leu','lei','Europe','Eastern Europe'],
            ['RU','Russia','RUS','7','Moscow','RUB','Russian Ruble','₽','Europe','Eastern Europe'],
            ['SM','San Marino','SMR','378','City of San Marino','EUR','Euro','€','Europe','Southern Europe'],
            ['RS','Serbia','SRB','381','Belgrade','RSD','Serbian Dinar','din','Europe','Southern Europe'],
            ['SK','Slovakia','SVK','421','Bratislava','EUR','Euro','€','Europe','Eastern Europe'],
            ['SI','Slovenia','SVN','386','Ljubljana','EUR','Euro','€','Europe','Southern Europe'],
            ['ES','Spain','ESP','34','Madrid','EUR','Euro','€','Europe','Southern Europe'],
            ['SE','Sweden','SWE','46','Stockholm','SEK','Swedish Krona','kr','Europe','Northern Europe'],
            ['CH','Switzerland','CHE','41','Bern','CHF','Swiss Franc','Fr','Europe','Western Europe'],
            ['UA','Ukraine','UKR','380','Kyiv','UAH','Ukrainian Hryvnia','₴','Europe','Eastern Europe'],
            ['GB','United Kingdom','GBR','44','London','GBP','British Pound Sterling','£','Europe','Northern Europe'],
            ['VA','Vatican City','VAT','379','Vatican City','EUR','Euro','€','Europe','Southern Europe'],

            // ── Americas ──────────────────────────────────────────────────────────
            ['AG','Antigua and Barbuda','ATG','1268',"Saint John's",'XCD','East Caribbean Dollar','$','Americas','Caribbean'],
            ['BS','Bahamas','BHS','1242','Nassau','BSD','Bahamian Dollar','$','Americas','Caribbean'],
            ['BB','Barbados','BRB','1246','Bridgetown','BBD','Barbadian Dollar','$','Americas','Caribbean'],
            ['BZ','Belize','BLZ','501','Belmopan','BZD','Belize Dollar','$','Americas','Central America'],
            ['CA','Canada','CAN','1','Ottawa','CAD','Canadian Dollar','$','Americas','Northern America'],
            ['CR','Costa Rica','CRI','506','San José','CRC','Costa Rican Colón','₡','Americas','Central America'],
            ['CU','Cuba','CUB','53','Havana','CUP','Cuban Peso','$','Americas','Caribbean'],
            ['DM','Dominica','DMA','1767','Roseau','XCD','East Caribbean Dollar','$','Americas','Caribbean'],
            ['DO','Dominican Republic','DOM','1809','Santo Domingo','DOP','Dominican Peso','$','Americas','Caribbean'],
            ['SV','El Salvador','SLV','503','San Salvador','USD','US Dollar','$','Americas','Central America'],
            ['GD','Grenada','GRD','1473',"Saint George's",'XCD','East Caribbean Dollar','$','Americas','Caribbean'],
            ['GT','Guatemala','GTM','502','Guatemala City','GTQ','Guatemalan Quetzal','Q','Americas','Central America'],
            ['HT','Haiti','HTI','509','Port-au-Prince','HTG','Haitian Gourde','G','Americas','Caribbean'],
            ['HN','Honduras','HND','504','Tegucigalpa','HNL','Honduran Lempira','L','Americas','Central America'],
            ['JM','Jamaica','JAM','1876','Kingston','JMD','Jamaican Dollar','$','Americas','Caribbean'],
            ['MX','Mexico','MEX','52','Mexico City','MXN','Mexican Peso','$','Americas','Central America'],
            ['NI','Nicaragua','NIC','505','Managua','NIO','Nicaraguan Córdoba','C$','Americas','Central America'],
            ['PA','Panama','PAN','507','Panama City','PAB','Panamanian Balboa','B/.','Americas','Central America'],
            ['KN','Saint Kitts and Nevis','KNA','1869','Basseterre','XCD','East Caribbean Dollar','$','Americas','Caribbean'],
            ['LC','Saint Lucia','LCA','1758','Castries','XCD','East Caribbean Dollar','$','Americas','Caribbean'],
            ['VC','Saint Vincent and the Grenadines','VCT','1784','Kingstown','XCD','East Caribbean Dollar','$','Americas','Caribbean'],
            ['TT','Trinidad and Tobago','TTO','1868','Port of Spain','TTD','Trinidad and Tobago Dollar','$','Americas','Caribbean'],
            ['US','United States','USA','1','Washington D.C.','USD','US Dollar','$','Americas','Northern America'],
            ['AR','Argentina','ARG','54','Buenos Aires','ARS','Argentine Peso','$','Americas','South America'],
            ['BO','Bolivia','BOL','591','Sucre','BOB','Bolivian Boliviano','Bs.','Americas','South America'],
            ['BR','Brazil','BRA','55','Brasilia','BRL','Brazilian Real','R$','Americas','South America'],
            ['CL','Chile','CHL','56','Santiago','CLP','Chilean Peso','$','Americas','South America'],
            ['CO','Colombia','COL','57','Bogotá','COP','Colombian Peso','$','Americas','South America'],
            ['EC','Ecuador','ECU','593','Quito','USD','US Dollar','$','Americas','South America'],
            ['GY','Guyana','GUY','592','Georgetown','GYD','Guyanese Dollar','$','Americas','South America'],
            ['PY','Paraguay','PRY','595','Asunción','PYG','Paraguayan Guaraní','₲','Americas','South America'],
            ['PE','Peru','PER','51','Lima','PEN','Peruvian Sol','S/','Americas','South America'],
            ['SR','Suriname','SUR','597','Paramaribo','SRD','Surinamese Dollar','$','Americas','South America'],
            ['UY','Uruguay','URY','598','Montevideo','UYU','Uruguayan Peso','$','Americas','South America'],
            ['VE','Venezuela','VEN','58','Caracas','VES','Venezuelan Bolívar Soberano','Bs.S','Americas','South America'],

            // ── Oceania ───────────────────────────────────────────────────────────
            ['AU','Australia','AUS','61','Canberra','AUD','Australian Dollar','$','Oceania','Australia and New Zealand'],
            ['FJ','Fiji','FJI','679','Suva','FJD','Fijian Dollar','$','Oceania','Melanesia'],
            ['KI','Kiribati','KIR','686','South Tarawa','AUD','Australian Dollar','$','Oceania','Micronesia'],
            ['MH','Marshall Islands','MHL','692','Majuro','USD','US Dollar','$','Oceania','Micronesia'],
            ['FM','Micronesia','FSM','691','Palikir','USD','US Dollar','$','Oceania','Micronesia'],
            ['NR','Nauru','NRU','674','Yaren','AUD','Australian Dollar','$','Oceania','Micronesia'],
            ['NZ','New Zealand','NZL','64','Wellington','NZD','New Zealand Dollar','$','Oceania','Australia and New Zealand'],
            ['PW','Palau','PLW','680','Ngerulmud','USD','US Dollar','$','Oceania','Micronesia'],
            ['PG','Papua New Guinea','PNG','675','Port Moresby','PGK','Papua New Guinean Kina','K','Oceania','Melanesia'],
            ['WS','Samoa','WSM','685','Apia','WST','Samoan Tālā','T','Oceania','Polynesia'],
            ['SB','Solomon Islands','SLB','677','Honiara','SBD','Solomon Islands Dollar','$','Oceania','Melanesia'],
            ['TO','Tonga','TON','676','Nukualofa','TOP',"Tongan Pa'anga",'T$','Oceania','Polynesia'],
            ['TV','Tuvalu','TUV','688','Funafuti','AUD','Australian Dollar','$','Oceania','Polynesia'],
            ['VU','Vanuatu','VUT','678','Port Vila','VUV','Vanuatu Vatu','Vt','Oceania','Melanesia'],
        ];

        foreach ($countries as $i => [$iso2, $name, $iso3, $phone, $capital, $cur_code, $cur_name, $cur_sym, $region, $subregion]) {
            Country::updateOrCreate(
                ['iso2' => $iso2],
                [
                    'name'            => $name,
                    'iso3'            => $iso3,
                    'phone_code'      => $phone,
                    'capital'         => $capital,
                    'currency_code'   => $cur_code,
                    'currency_name'   => $cur_name,
                    'currency_symbol' => $cur_sym,
                    'region'          => $region,
                    'subregion'       => $subregion,
                    'flag_emoji'      => $this->flagEmoji($iso2),
                    'is_active'       => true,
                    'sort_order'      => $i + 1,
                ]
            );
        }

        $this->command->info('Countries seeded: ' . count($countries));
    }

    private function flagEmoji(string $iso2): string
    {
        return implode('', array_map(
            fn (string $char) => mb_chr(0x1F1E6 + ord($char) - 65),
            str_split(strtoupper($iso2))
        ));
    }
}
