<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            ['code' => 'AED', 'name' => 'UAE Dirham',                     'country' => 'United Arab Emirates', 'symbol' => 'د.إ'],
            ['code' => 'AFN', 'name' => 'Afghan Afghani',                  'country' => 'Afghanistan',           'symbol' => '؋'],
            ['code' => 'ALL', 'name' => 'Albanian Lek',                    'country' => 'Albania',               'symbol' => 'L'],
            ['code' => 'AMD', 'name' => 'Armenian Dram',                   'country' => 'Armenia',               'symbol' => '֏'],
            ['code' => 'ANG', 'name' => 'Netherlands Antillean Guilder',   'country' => 'Netherlands Antilles',  'symbol' => 'ƒ'],
            ['code' => 'AOA', 'name' => 'Angolan Kwanza',                  'country' => 'Angola',                'symbol' => 'Kz'],
            ['code' => 'ARS', 'name' => 'Argentine Peso',                  'country' => 'Argentina',             'symbol' => '$'],
            ['code' => 'AUD', 'name' => 'Australian Dollar',               'country' => 'Australia',             'symbol' => 'A$'],
            ['code' => 'AWG', 'name' => 'Aruban Florin',                   'country' => 'Aruba',                 'symbol' => 'ƒ'],
            ['code' => 'AZN', 'name' => 'Azerbaijani Manat',               'country' => 'Azerbaijan',            'symbol' => '₼'],
            ['code' => 'BAM', 'name' => 'Bosnia-Herzegovina Mark',         'country' => 'Bosnia & Herzegovina',  'symbol' => 'KM'],
            ['code' => 'BBD', 'name' => 'Barbadian Dollar',                'country' => 'Barbados',              'symbol' => 'Bds$'],
            ['code' => 'BDT', 'name' => 'Bangladeshi Taka',                'country' => 'Bangladesh',            'symbol' => '৳'],
            ['code' => 'BGN', 'name' => 'Bulgarian Lev',                   'country' => 'Bulgaria',              'symbol' => 'лв'],
            ['code' => 'BHD', 'name' => 'Bahraini Dinar',                  'country' => 'Bahrain',               'symbol' => '.د.ب'],
            ['code' => 'BIF', 'name' => 'Burundian Franc',                 'country' => 'Burundi',               'symbol' => 'Fr'],
            ['code' => 'BMD', 'name' => 'Bermudan Dollar',                 'country' => 'Bermuda',               'symbol' => '$'],
            ['code' => 'BND', 'name' => 'Brunei Dollar',                   'country' => 'Brunei',                'symbol' => 'B$'],
            ['code' => 'BOB', 'name' => 'Bolivian Boliviano',              'country' => 'Bolivia',               'symbol' => 'Bs.'],
            ['code' => 'BRL', 'name' => 'Brazilian Real',                  'country' => 'Brazil',                'symbol' => 'R$'],
            ['code' => 'BSD', 'name' => 'Bahamian Dollar',                 'country' => 'Bahamas',               'symbol' => '$'],
            ['code' => 'BTN', 'name' => 'Bhutanese Ngultrum',              'country' => 'Bhutan',                'symbol' => 'Nu'],
            ['code' => 'BWP', 'name' => 'Botswanan Pula',                  'country' => 'Botswana',              'symbol' => 'P'],
            ['code' => 'BYN', 'name' => 'Belarusian Ruble',                'country' => 'Belarus',               'symbol' => 'Br'],
            ['code' => 'BZD', 'name' => 'Belize Dollar',                   'country' => 'Belize',                'symbol' => 'BZ$'],
            ['code' => 'CAD', 'name' => 'Canadian Dollar',                 'country' => 'Canada',                'symbol' => 'C$'],
            ['code' => 'CDF', 'name' => 'Congolese Franc',                 'country' => 'DR Congo',              'symbol' => 'Fr'],
            ['code' => 'CHF', 'name' => 'Swiss Franc',                     'country' => 'Switzerland',           'symbol' => 'Fr'],
            ['code' => 'CLP', 'name' => 'Chilean Peso',                    'country' => 'Chile',                 'symbol' => '$'],
            ['code' => 'CNY', 'name' => 'Chinese Yuan',                    'country' => 'China',                 'symbol' => '¥'],
            ['code' => 'COP', 'name' => 'Colombian Peso',                  'country' => 'Colombia',              'symbol' => '$'],
            ['code' => 'CRC', 'name' => 'Costa Rican Colón',               'country' => 'Costa Rica',            'symbol' => '₡'],
            ['code' => 'CUP', 'name' => 'Cuban Peso',                      'country' => 'Cuba',                  'symbol' => '$'],
            ['code' => 'CVE', 'name' => 'Cape Verdean Escudo',             'country' => 'Cape Verde',            'symbol' => '$'],
            ['code' => 'CZK', 'name' => 'Czech Koruna',                    'country' => 'Czech Republic',        'symbol' => 'Kč'],
            ['code' => 'DJF', 'name' => 'Djiboutian Franc',                'country' => 'Djibouti',              'symbol' => 'Fr'],
            ['code' => 'DKK', 'name' => 'Danish Krone',                    'country' => 'Denmark',               'symbol' => 'kr'],
            ['code' => 'DOP', 'name' => 'Dominican Peso',                  'country' => 'Dominican Republic',    'symbol' => 'RD$'],
            ['code' => 'DZD', 'name' => 'Algerian Dinar',                  'country' => 'Algeria',               'symbol' => 'د.ج'],
            ['code' => 'EGP', 'name' => 'Egyptian Pound',                  'country' => 'Egypt',                 'symbol' => '£'],
            ['code' => 'ETB', 'name' => 'Ethiopian Birr',                  'country' => 'Ethiopia',              'symbol' => 'Br'],
            ['code' => 'EUR', 'name' => 'Euro',                            'country' => 'European Union',        'symbol' => '€'],
            ['code' => 'FJD', 'name' => 'Fijian Dollar',                   'country' => 'Fiji',                  'symbol' => '$'],
            ['code' => 'GBP', 'name' => 'British Pound Sterling',          'country' => 'United Kingdom',        'symbol' => '£'],
            ['code' => 'GEL', 'name' => 'Georgian Lari',                   'country' => 'Georgia',               'symbol' => '₾'],
            ['code' => 'GHS', 'name' => 'Ghanaian Cedi',                   'country' => 'Ghana',                 'symbol' => '₵'],
            ['code' => 'GMD', 'name' => 'Gambian Dalasi',                  'country' => 'Gambia',                'symbol' => 'D'],
            ['code' => 'GTQ', 'name' => 'Guatemalan Quetzal',              'country' => 'Guatemala',             'symbol' => 'Q'],
            ['code' => 'GYD', 'name' => 'Guyanaese Dollar',                'country' => 'Guyana',                'symbol' => '$'],
            ['code' => 'HKD', 'name' => 'Hong Kong Dollar',                'country' => 'Hong Kong',             'symbol' => 'HK$'],
            ['code' => 'HNL', 'name' => 'Honduran Lempira',                'country' => 'Honduras',              'symbol' => 'L'],
            ['code' => 'HTG', 'name' => 'Haitian Gourde',                  'country' => 'Haiti',                 'symbol' => 'G'],
            ['code' => 'HUF', 'name' => 'Hungarian Forint',                'country' => 'Hungary',               'symbol' => 'Ft'],
            ['code' => 'IDR', 'name' => 'Indonesian Rupiah',               'country' => 'Indonesia',             'symbol' => 'Rp'],
            ['code' => 'ILS', 'name' => 'Israeli New Shekel',              'country' => 'Israel',                'symbol' => '₪'],
            ['code' => 'INR', 'name' => 'Indian Rupee',                    'country' => 'India',                 'symbol' => '₹'],
            ['code' => 'IQD', 'name' => 'Iraqi Dinar',                     'country' => 'Iraq',                  'symbol' => 'ع.د'],
            ['code' => 'IRR', 'name' => 'Iranian Rial',                    'country' => 'Iran',                  'symbol' => '﷼'],
            ['code' => 'ISK', 'name' => 'Icelandic Króna',                 'country' => 'Iceland',               'symbol' => 'kr'],
            ['code' => 'JMD', 'name' => 'Jamaican Dollar',                 'country' => 'Jamaica',               'symbol' => 'J$'],
            ['code' => 'JOD', 'name' => 'Jordanian Dinar',                 'country' => 'Jordan',                'symbol' => 'JD'],
            ['code' => 'JPY', 'name' => 'Japanese Yen',                    'country' => 'Japan',                 'symbol' => '¥'],
            ['code' => 'KES', 'name' => 'Kenyan Shilling',                 'country' => 'Kenya',                 'symbol' => 'KSh'],
            ['code' => 'KGS', 'name' => 'Kyrgystani Som',                  'country' => 'Kyrgyzstan',            'symbol' => 'с'],
            ['code' => 'KHR', 'name' => 'Cambodian Riel',                  'country' => 'Cambodia',              'symbol' => '៛'],
            ['code' => 'KRW', 'name' => 'South Korean Won',                'country' => 'South Korea',           'symbol' => '₩'],
            ['code' => 'KWD', 'name' => 'Kuwaiti Dinar',                   'country' => 'Kuwait',                'symbol' => 'KD'],
            ['code' => 'KYD', 'name' => 'Cayman Islands Dollar',           'country' => 'Cayman Islands',        'symbol' => '$'],
            ['code' => 'KZT', 'name' => 'Kazakhstani Tenge',               'country' => 'Kazakhstan',            'symbol' => '₸'],
            ['code' => 'LAK', 'name' => 'Laotian Kip',                     'country' => 'Laos',                  'symbol' => '₭'],
            ['code' => 'LBP', 'name' => 'Lebanese Pound',                  'country' => 'Lebanon',               'symbol' => 'ل.ل'],
            ['code' => 'LKR', 'name' => 'Sri Lankan Rupee',                'country' => 'Sri Lanka',             'symbol' => 'Rs', 'is_default' => true],
            ['code' => 'LRD', 'name' => 'Liberian Dollar',                 'country' => 'Liberia',               'symbol' => '$'],
            ['code' => 'LYD', 'name' => 'Libyan Dinar',                    'country' => 'Libya',                 'symbol' => 'LD'],
            ['code' => 'MAD', 'name' => 'Moroccan Dirham',                 'country' => 'Morocco',               'symbol' => 'MAD'],
            ['code' => 'MDL', 'name' => 'Moldovan Leu',                    'country' => 'Moldova',               'symbol' => 'L'],
            ['code' => 'MGA', 'name' => 'Malagasy Ariary',                 'country' => 'Madagascar',            'symbol' => 'Ar'],
            ['code' => 'MKD', 'name' => 'Macedonian Denar',                'country' => 'North Macedonia',       'symbol' => 'ден'],
            ['code' => 'MMK', 'name' => 'Myanmar Kyat',                    'country' => 'Myanmar',               'symbol' => 'K'],
            ['code' => 'MNT', 'name' => 'Mongolian Tugrik',                'country' => 'Mongolia',              'symbol' => '₮'],
            ['code' => 'MOP', 'name' => 'Macanese Pataca',                 'country' => 'Macau',                 'symbol' => 'P'],
            ['code' => 'MUR', 'name' => 'Mauritian Rupee',                 'country' => 'Mauritius',             'symbol' => 'Rs'],
            ['code' => 'MVR', 'name' => 'Maldivian Rufiyaa',               'country' => 'Maldives',              'symbol' => 'Rf'],
            ['code' => 'MWK', 'name' => 'Malawian Kwacha',                 'country' => 'Malawi',                'symbol' => 'MK'],
            ['code' => 'MXN', 'name' => 'Mexican Peso',                    'country' => 'Mexico',                'symbol' => '$'],
            ['code' => 'MYR', 'name' => 'Malaysian Ringgit',               'country' => 'Malaysia',              'symbol' => 'RM'],
            ['code' => 'MZN', 'name' => 'Mozambican Metical',              'country' => 'Mozambique',            'symbol' => 'MT'],
            ['code' => 'NAD', 'name' => 'Namibian Dollar',                 'country' => 'Namibia',               'symbol' => '$'],
            ['code' => 'NGN', 'name' => 'Nigerian Naira',                  'country' => 'Nigeria',               'symbol' => '₦'],
            ['code' => 'NIO', 'name' => 'Nicaraguan Córdoba',              'country' => 'Nicaragua',             'symbol' => 'C$'],
            ['code' => 'NOK', 'name' => 'Norwegian Krone',                 'country' => 'Norway',                'symbol' => 'kr'],
            ['code' => 'NPR', 'name' => 'Nepalese Rupee',                  'country' => 'Nepal',                 'symbol' => 'Rs'],
            ['code' => 'NZD', 'name' => 'New Zealand Dollar',              'country' => 'New Zealand',           'symbol' => '$'],
            ['code' => 'OMR', 'name' => 'Omani Rial',                      'country' => 'Oman',                  'symbol' => 'ر.ع.'],
            ['code' => 'PAB', 'name' => 'Panamanian Balboa',               'country' => 'Panama',                'symbol' => 'B/.'],
            ['code' => 'PEN', 'name' => 'Peruvian Sol',                    'country' => 'Peru',                  'symbol' => 'S/.'],
            ['code' => 'PGK', 'name' => 'Papua New Guinean Kina',          'country' => 'Papua New Guinea',      'symbol' => 'K'],
            ['code' => 'PHP', 'name' => 'Philippine Peso',                 'country' => 'Philippines',           'symbol' => '₱'],
            ['code' => 'PKR', 'name' => 'Pakistani Rupee',                 'country' => 'Pakistan',              'symbol' => 'Rs'],
            ['code' => 'PLN', 'name' => 'Polish Zloty',                    'country' => 'Poland',                'symbol' => 'zł'],
            ['code' => 'PYG', 'name' => 'Paraguayan Guarani',              'country' => 'Paraguay',              'symbol' => '₲'],
            ['code' => 'QAR', 'name' => 'Qatari Rial',                     'country' => 'Qatar',                 'symbol' => 'ر.ق'],
            ['code' => 'RON', 'name' => 'Romanian Leu',                    'country' => 'Romania',               'symbol' => 'lei'],
            ['code' => 'RSD', 'name' => 'Serbian Dinar',                   'country' => 'Serbia',                'symbol' => 'din'],
            ['code' => 'RUB', 'name' => 'Russian Ruble',                   'country' => 'Russia',                'symbol' => '₽'],
            ['code' => 'RWF', 'name' => 'Rwandan Franc',                   'country' => 'Rwanda',                'symbol' => 'Fr'],
            ['code' => 'SAR', 'name' => 'Saudi Riyal',                     'country' => 'Saudi Arabia',          'symbol' => 'ر.س'],
            ['code' => 'SBD', 'name' => 'Solomon Islands Dollar',          'country' => 'Solomon Islands',       'symbol' => '$'],
            ['code' => 'SCR', 'name' => 'Seychellois Rupee',               'country' => 'Seychelles',            'symbol' => 'Rs'],
            ['code' => 'SDG', 'name' => 'Sudanese Pound',                  'country' => 'Sudan',                 'symbol' => 'ج.س.'],
            ['code' => 'SEK', 'name' => 'Swedish Krona',                   'country' => 'Sweden',                'symbol' => 'kr'],
            ['code' => 'SGD', 'name' => 'Singapore Dollar',                'country' => 'Singapore',             'symbol' => 'S$'],
            ['code' => 'SOS', 'name' => 'Somali Shilling',                 'country' => 'Somalia',               'symbol' => 'Sh'],
            ['code' => 'SRD', 'name' => 'Surinamese Dollar',               'country' => 'Suriname',              'symbol' => '$'],
            ['code' => 'STN', 'name' => 'São Tomé & Príncipe Dobra',       'country' => 'São Tomé & Príncipe',   'symbol' => 'Db'],
            ['code' => 'SYP', 'name' => 'Syrian Pound',                    'country' => 'Syria',                 'symbol' => '£'],
            ['code' => 'SZL', 'name' => 'Swazi Lilangeni',                 'country' => 'Eswatini',              'symbol' => 'L'],
            ['code' => 'THB', 'name' => 'Thai Baht',                       'country' => 'Thailand',              'symbol' => '฿'],
            ['code' => 'TJS', 'name' => 'Tajikistani Somoni',              'country' => 'Tajikistan',            'symbol' => 'SM'],
            ['code' => 'TMT', 'name' => 'Turkmenistani Manat',             'country' => 'Turkmenistan',          'symbol' => 'T'],
            ['code' => 'TND', 'name' => 'Tunisian Dinar',                  'country' => 'Tunisia',               'symbol' => 'DT'],
            ['code' => 'TOP', 'name' => 'Tongan Paʻanga',                  'country' => 'Tonga',                 'symbol' => 'T$'],
            ['code' => 'TRY', 'name' => 'Turkish Lira',                    'country' => 'Turkey',                'symbol' => '₺'],
            ['code' => 'TTD', 'name' => 'Trinidad & Tobago Dollar',        'country' => 'Trinidad & Tobago',     'symbol' => 'TT$'],
            ['code' => 'TWD', 'name' => 'New Taiwan Dollar',               'country' => 'Taiwan',                'symbol' => 'NT$'],
            ['code' => 'TZS', 'name' => 'Tanzanian Shilling',              'country' => 'Tanzania',              'symbol' => 'Sh'],
            ['code' => 'UAH', 'name' => 'Ukrainian Hryvnia',               'country' => 'Ukraine',               'symbol' => '₴'],
            ['code' => 'UGX', 'name' => 'Ugandan Shilling',                'country' => 'Uganda',                'symbol' => 'Sh'],
            ['code' => 'USD', 'name' => 'US Dollar',                       'country' => 'United States',         'symbol' => '$'],
            ['code' => 'UYU', 'name' => 'Uruguayan Peso',                  'country' => 'Uruguay',               'symbol' => '$'],
            ['code' => 'UZS', 'name' => 'Uzbekistani Som',                 'country' => 'Uzbekistan',            'symbol' => "so'm"],
            ['code' => 'VND', 'name' => 'Vietnamese Dong',                 'country' => 'Vietnam',               'symbol' => '₫'],
            ['code' => 'VUV', 'name' => 'Vanuatu Vatu',                    'country' => 'Vanuatu',               'symbol' => 'Vt'],
            ['code' => 'WST', 'name' => 'Samoan Tala',                     'country' => 'Samoa',                 'symbol' => 'WS$'],
            ['code' => 'XAF', 'name' => 'CFA Franc BEAC',                  'country' => 'Central Africa',        'symbol' => 'Fr'],
            ['code' => 'XCD', 'name' => 'East Caribbean Dollar',           'country' => 'East Caribbean',        'symbol' => '$'],
            ['code' => 'XOF', 'name' => 'CFA Franc BCEAO',                 'country' => 'West Africa',           'symbol' => 'Fr'],
            ['code' => 'XPF', 'name' => 'CFP Franc',                       'country' => 'French Polynesia',      'symbol' => 'Fr'],
            ['code' => 'YER', 'name' => 'Yemeni Rial',                     'country' => 'Yemen',                 'symbol' => '﷼'],
            ['code' => 'ZAR', 'name' => 'South African Rand',              'country' => 'South Africa',          'symbol' => 'R'],
            ['code' => 'ZMW', 'name' => 'Zambian Kwacha',                  'country' => 'Zambia',                'symbol' => 'ZK'],
            ['code' => 'ZWL', 'name' => 'Zimbabwean Dollar',               'country' => 'Zimbabwe',              'symbol' => '$'],
        ];

        $now = now();
        foreach ($currencies as $i => $currency) {
            Currency::updateOrCreate(
                ['code' => $currency['code']],
                array_merge([
                    'is_default' => false,
                    'is_active'  => true,
                    'sort_order' => $i + 1,
                    'created_at' => $now,
                    'updated_at' => $now,
                ], $currency)
            );
        }
    }
}
