<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\CustomerType;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    private array $typeMap = [
        'shipping_line'     => ['Shipping Line'],
        'freight_forwarder' => ['Forwarder'],
        'depot_owner'       => ['Local Yard'],
        'nvo_carrier'       => ['NVOCC'],
        'leasing_company'   => ['Container Operator'],
    ];

    public function run(): void
    {
        $customers = [
            [
                'code'            => 'MSK',
                'name'            => 'Maersk Line Malaysia Sdn Bhd',
                '_types'          => 'shipping_line',
                'registration_no' => '199301012345',
                'address'         => 'Level 25, Menara Maxis, Kuala Lumpur City Centre',
                'city'            => 'Kuala Lumpur',
                'state'           => 'W.P. Kuala Lumpur',
                'country'         => 'Malaysia',
                'contact_person'  => 'James Tan',
                'designation'     => 'Operations Manager',
                'phone_office'    => '012-3334455',
                'phone_mobile'    => '+60123456001',
                'email'           => 'james@maersk.com',
                'currency'        => 'USD',
                'credit_limit'    => 500000.00,
                'payment_terms'   => 'net30',
                'status'          => 'active',
                'contract_start'  => '2024-01-01',
                'contract_end'    => '2025-12-31',
                'email_notifications' => true,
                'auto_invoice'    => true,
            ],
            [
                'code'            => 'CMA',
                'name'            => 'CMA CGM (Malaysia) Sdn Bhd',
                '_types'          => 'shipping_line',
                'registration_no' => '200001023456',
                'address'         => 'Suite 12-1, Menara IGB, Mid Valley City',
                'city'            => 'Kuala Lumpur',
                'state'           => 'W.P. Kuala Lumpur',
                'country'         => 'Malaysia',
                'contact_person'  => 'Sophie Lim',
                'designation'     => 'Container Manager',
                'phone_office'    => '019-8887766',
                'phone_mobile'    => '+60123456002',
                'email'           => 'sophie@cmacgm.com',
                'currency'        => 'USD',
                'credit_limit'    => 350000.00,
                'payment_terms'   => 'net30',
                'status'          => 'active',
                'contract_start'  => '2024-01-01',
                'contract_end'    => '2025-12-31',
                'email_notifications' => true,
                'auto_invoice'    => true,
            ],
            [
                'code'            => 'PIL',
                'name'            => 'Pacific International Lines (M) Sdn Bhd',
                '_types'          => 'shipping_line',
                'registration_no' => '199801034567',
                'address'         => 'Jalan Tun Abdul Razak, Johor Bahru',
                'city'            => 'Johor Bahru',
                'state'           => 'Johor',
                'country'         => 'Malaysia',
                'contact_person'  => 'Rajan Kumar',
                'designation'     => 'Depot Coordinator',
                'phone_office'    => '013-2221100',
                'phone_mobile'    => '+60123456003',
                'email'           => 'rajan@pilship.com',
                'currency'        => 'USD',
                'credit_limit'    => 200000.00,
                'payment_terms'   => 'net15',
                'status'          => 'active',
                'contract_start'  => '2024-03-01',
                'contract_end'    => '2026-02-28',
                'email_notifications' => true,
                'auto_invoice'    => false,
            ],
            [
                'code'            => 'HAP',
                'name'            => 'Hapag-Lloyd Malaysia Sdn Bhd',
                '_types'          => 'shipping_line',
                'registration_no' => '200501045678',
                'address'         => 'Level 18, Menara AmBank, Jalan Yap Kwan Seng',
                'city'            => 'Kuala Lumpur',
                'state'           => 'W.P. Kuala Lumpur',
                'country'         => 'Malaysia',
                'contact_person'  => 'Maria Wong',
                'designation'     => 'Regional Manager',
                'phone_office'    => '016-5556677',
                'phone_mobile'    => '+60123456004',
                'email'           => 'maria@hapag.com',
                'currency'        => 'USD',
                'credit_limit'    => 400000.00,
                'payment_terms'   => 'net30',
                'status'          => 'active',
                'contract_start'  => '2024-01-01',
                'contract_end'    => '2025-12-31',
                'email_notifications' => true,
                'auto_invoice'    => true,
            ],
            [
                'code'            => 'OOC',
                'name'            => 'OOCL Malaysia Sdn Bhd',
                '_types'          => 'shipping_line',
                'registration_no' => '199901056789',
                'address'         => 'Wisma Consplant 1, Jalan SS 16/4, Subang Jaya',
                'city'            => 'Subang Jaya',
                'state'           => 'Selangor',
                'country'         => 'Malaysia',
                'contact_person'  => 'David Lee',
                'designation'     => 'Container Controller',
                'phone_office'    => '017-9990011',
                'phone_mobile'    => '+60123456005',
                'email'           => 'david@oocl.com',
                'currency'        => 'USD',
                'credit_limit'    => 180000.00,
                'payment_terms'   => 'net30',
                'status'          => 'active',
                'contract_start'  => '2024-02-01',
                'contract_end'    => '2025-01-31',
                'email_notifications' => true,
                'auto_invoice'    => true,
            ],
            [
                'code'            => 'EVG',
                'name'            => 'Evergreen Marine (Malaysia) Sdn Bhd',
                '_types'          => 'shipping_line',
                'registration_no' => '200201067890',
                'address'         => 'Tingkat 12, Menara Shell, Jalan Tun Sambanthan',
                'city'            => 'Kuala Lumpur',
                'state'           => 'W.P. Kuala Lumpur',
                'country'         => 'Malaysia',
                'contact_person'  => 'Chen Wei',
                'designation'     => 'Operations Executive',
                'phone_office'    => '011-22334455',
                'phone_mobile'    => '+60123456006',
                'email'           => 'chen@evergreen.com',
                'currency'        => 'USD',
                'credit_limit'    => 220000.00,
                'payment_terms'   => 'net30',
                'status'          => 'active',
                'contract_start'  => '2024-01-01',
                'contract_end'    => '2025-12-31',
                'email_notifications' => false,
                'auto_invoice'    => true,
            ],
            [
                'code'            => 'MSC',
                'name'            => 'MSC Malaysia Sdn Bhd',
                '_types'          => 'shipping_line',
                'registration_no' => '200801078901',
                'address'         => 'Suite 6-1, Menara Landmark, Jalan Bukit Bintang',
                'city'            => 'Kuala Lumpur',
                'state'           => 'W.P. Kuala Lumpur',
                'country'         => 'Malaysia',
                'contact_person'  => 'Anwar Hussain',
                'designation'     => 'Depot Manager',
                'phone_office'    => '018-6665544',
                'phone_mobile'    => '+60123456007',
                'email'           => 'anwar@msc.com',
                'currency'        => 'USD',
                'credit_limit'    => 300000.00,
                'payment_terms'   => 'net45',
                'status'          => 'active',
                'contract_start'  => '2024-06-01',
                'contract_end'    => '2025-05-31',
                'email_notifications' => true,
                'auto_invoice'    => true,
            ],
            [
                'code'            => 'ZIM',
                'name'            => 'Zim Integrated Shipping Services (M) Sdn Bhd',
                '_types'          => 'nvo_carrier',
                'registration_no' => '201001089012',
                'address'         => 'Jalan Pelabuhan, Port Klang',
                'city'            => 'Port Klang',
                'state'           => 'Selangor',
                'country'         => 'Malaysia',
                'contact_person'  => 'Tan Ah Kow',
                'designation'     => 'Logistics Coordinator',
                'phone_office'    => '014-1112233',
                'phone_mobile'    => '+60123456008',
                'email'           => 'tan@zim.com',
                'currency'        => 'USD',
                'credit_limit'    => 80000.00,
                'payment_terms'   => 'net30',
                'status'          => 'inactive',
                'contract_start'  => '2023-01-01',
                'contract_end'    => '2023-12-31',
                'email_notifications' => false,
                'auto_invoice'    => false,
            ],
            [
                'code'            => 'FRX',
                'name'            => 'Freight Express Sdn Bhd',
                '_types'          => 'freight_forwarder',
                'registration_no' => '201501090123',
                'address'         => 'No. 12, Jalan Perindustrian, Kawasan Perindustrian Pandamaran',
                'city'            => 'Port Klang',
                'state'           => 'Selangor',
                'country'         => 'Malaysia',
                'contact_person'  => 'Azwan Omar',
                'designation'     => 'Managing Director',
                'phone_office'    => '015-3334411',
                'phone_mobile'    => '+60123456009',
                'email'           => 'azwan@frx.com.my',
                'currency'        => 'LKR',
                'credit_limit'    => 120000.00,
                'payment_terms'   => 'net30',
                'status'          => 'pending',
                'contract_start'  => '2025-01-01',
                'contract_end'    => '2025-12-31',
                'email_notifications' => true,
                'auto_invoice'    => false,
            ],
            [
                'code'            => 'PDB',
                'name'            => 'Port Depot Berhad',
                '_types'          => 'depot_owner',
                'registration_no' => '201201101234',
                'address'         => 'Lot 5, Jalan Pelabuhan Barat, Pulau Indah Industrial Park',
                'city'            => 'Port Klang',
                'state'           => 'Selangor',
                'country'         => 'Malaysia',
                'contact_person'  => 'Lim Siew Ching',
                'designation'     => 'General Manager',
                'phone_office'    => '012-7778899',
                'phone_mobile'    => '+60123456010',
                'email'           => 'lim@pdb.com.my',
                'currency'        => 'LKR',
                'credit_limit'    => 50000.00,
                'payment_terms'   => 'net15',
                'status'          => 'pending',
                'contract_start'  => '2025-01-01',
                'contract_end'    => '2025-12-31',
                'email_notifications' => true,
                'auto_invoice'    => false,
            ],
        ];

        foreach ($customers as $data) {
            $oldType = $data['_types'] ?? null;
            unset($data['_types']);

            $customer = Customer::firstOrCreate(['code' => $data['code']], $data);

            if ($oldType && isset($this->typeMap[$oldType])) {
                $typeIds = CustomerType::whereIn('name', $this->typeMap[$oldType])->pluck('id');
                $customer->types()->syncWithoutDetaching($typeIds);
            }
        }
    }
}
